version: 2.1

# -------------------------
#        EXECUTORS
# -------------------------
executors:
  node:
    docker:
      - image: circleci/node:lts

# -------------------------
#        COMMANDS
# -------------------------
commands:
  restore_cache_checkout:
    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}

  run_yarn:
    steps:
      - restore_cache:
          keys:
            - v1-yarn-{{ .Branch }}
      - run:
          name: Yarn Install
          command: yarn install --no-progress --non-interactive --cache-folder ~/.cache/yarn
      - save_cache:
          paths:
            - node_modules
            - ~/.cache/yarn
          key: v1-yarn-{{ .Branch }}

# -------------------------
#        JOBS
# -------------------------
jobs:
  # --------------------------------------------------
  # JOB: setup
  # Checks out the repo, and persists to cache.
  # --------------------------------------------------
  setup:
    executor: node
    working_directory: ~/react-native-website
    steps:
      - checkout
      - save_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/react-native-website

  # --------------------------------------------------
  # JOB: test
  # Test that the website can be built.
  # --------------------------------------------------
  test:
    executor: node
    working_directory: ~/react-native-website/website
    steps:
      - restore_cache_checkout
      - run_yarn
      - run: yarn ci-check
      - run: export NODE_OPTIONS=--max_old_space_size=4096
      - run: export TERSER_PARALLEL=false
      # Run build test only for three latest version to avoid memory issues
      - run: export DEPOLY_PREVIEW=true
      - run:
          name: Compile website
          command: yarn test
          no_output_timeout: 20m
      - run:
          name: Check for missing index.html (build errors)
          command: |
            if [ ! -f build/index.html ]; then
              exit 1;
            fi
  # --------------------------------------------------
  # JOB: lint
  # Lint the docs.
  # --------------------------------------------------
  language_lint:
    executor: node
    working_directory: ~/react-native-website/website
    steps:
      - restore_cache_checkout
      - run_yarn
      - run: yarn lint

# -------------------------
#        WORKFLOWS
# -------------------------
workflows:
  # Tests run on master and on forks
  tests:
    jobs:
      - setup

      # Run tests
      - test:
          requires:
            - setup

      # Run lints
      - language_lint:
          requires:
            - setup
